FROM ubuntu:noble
MAINTAINER Daniel Sobe <daniel.sobe@sorben.com>

# normal call
# docker build -f Dockerfile.cuda --build-arg NVIDIA_DRIVER_PACKAGE= --build-arg NVIDIA_DRIVER_VERSION= --progress=plain -t bamborak_backend_cuda .

# rebuild from scratch
# <... same cmdline ...>  -t bamborak_backend_cuda . --no-cache

WORKDIR /usr/app/src

RUN apt update

RUN apt install -y libsndfile1 sox libsox-fmt-all

# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# ENV PATH="/root/.cargo/bin:${PATH}"

#RUN apt install -y zlib1g zlib1g-dev libssl-dev libbz2-dev uuid-dev libsqlite3-dev liblzma-dev wget libffi-dev gcc g++ make
#RUN wget https://www.python.org/ftp/python/3.11.11/Python-3.11.11.tgz
#RUN tar xvfz Python-3.11.11.tgz
#RUN cd Python-3.11.11/ && ./configure --enable-optimizations && make -j && make altinstall


RUN apt install -y python3-pip python3-venv
RUN apt install -y python3-setuptools python3-distutils-extra

COPY requirements.txt requirements_pinned_cuda.txt requirements_voice_changer.txt /

# RUN cat /requirements_voice_changer.txt >> /requirements_pinned_cuda.txt

# code to generate a file with pinned versions 
# RUN pip install -r /requirements.txt
# RUN pip freeze

RUN cd /usr/app/src && python3 -m venv .

# avoid install failures later by making sure environment is up to date
#RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && python3 -m ensurepip --upgrade'
#RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && python3 -m pip install --upgrade setuptools'

RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && pip install coqui-tts==0.27.2'
RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && pip install -r /requirements_voice_changer.txt'
RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && pip install Flask==3.1.2 flask-cors==6.0.1'

# do this for old NVIDIA cards
RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126'

# install OpenVoice from sources

RUN apt update
RUN apt install -y git pkgconf libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev ffmpeg

RUN touch test

RUN git clone https://github.com/ZalozbaDev/OpenVoice /usr/app/src/OpenVoice

RUN cd /usr/app/src && /bin/bash -c 'source bin/activate && cd OpenVoice && git checkout c74f274e32cedb48479500d59aacf57b757541bb && pip install -e .'

RUN apt install -y nvidia-cuda-toolkit 

# try to force a fixed version
ARG NVIDIA_DRIVER_PACKAGE
ARG NVIDIA_DRIVER_VERSION

RUN apt install -y $NVIDIA_DRIVER_PACKAGE=$NVIDIA_DRIVER_VERSION

# no idea how to pipe nvidia device through at build time
# RUN nvidia-smi || echo "!!! Driver/Library mismatch!!!"

RUN mkdir temp
RUN mkdir logs

COPY ./ /usr/app/src/

RUN mkdir tts_models voice_changer

EXPOSE 8080

RUN chmod u+x start.sh

CMD ["./start.sh", "logs"]
