# normal call
# docker build -f Dockerfile.py312.cuda --build-arg NVIDIA_DRIVER_PACKAGE= --build-arg NVIDIA_DRIVER_VERSION= --progress=plain -t bamborak_backend_cuda_minimal .

# rebuild from scratch
# <... same cmdline ...>  -t bamborak_backend_cuda_minimal . --no-cache

# ==============================
# Stage 1 – Builder
# ==============================
FROM ubuntu:noble AS bamborak_ubuntu_builder

WORKDIR /opt/build

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-venv python3-pip \
    git pkgconf \
    libavformat-dev libavcodec-dev libavdevice-dev \
    libavutil-dev libavfilter-dev libswscale-dev libswresample-dev \
    ffmpeg curl librust-openssl-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# venv außerhalb vom App-Ordner (bessere Cachebarkeit)
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# install rust for the case of rebuilding python packages (transformers)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

COPY requirements_voice_changer.txt /

RUN pip install --upgrade pip setuptools wheel

# Install ML stack passend zu Coqui 0.27.5
RUN pip install torch==2.10.0+cu126 torchvision==0.25.0+cu126 torchaudio==2.10.0+cu126 \
    --index-url https://download.pytorch.org/whl/cu126
RUN pip install transformers==4.25.1 tokenizers==0.13.3
RUN pip install coqui-tts==0.27.5
RUN pip install Flask==3.1.2 flask-cors==6.0.1

# ---- OpenVoice separat (Cache bei Git SHA fix)
RUN git clone https://github.com/ZalozbaDev/OpenVoice /opt/OpenVoice \
    && cd /opt/OpenVoice \
    && git checkout c74f274e32cedb48479500d59aacf57b757541bb \
    && pip install -e .

# ==============================
# Stage 2 – Runtime (minimal!)
# ==============================
FROM ubuntu:noble

WORKDIR /usr/app/src

# try to force a fixed version
ARG NVIDIA_DRIVER_PACKAGE
ARG NVIDIA_DRIVER_VERSION

# nur Runtime-Libraries (KEINE dev!)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    libsndfile1 sox libsox-fmt-all \
    ffmpeg \
    $NVIDIA_DRIVER_PACKAGE=$NVIDIA_DRIVER_VERSION \
    && rm -rf /var/lib/apt/lists/*

# venv vom Builder übernehmen
COPY --from=bamborak_ubuntu_builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# App-Code zuletzt kopieren → C++ Rebuild nur bei Codeänderung
COPY . .

RUN mkdir -p logs temp tts_models voice_changer

EXPOSE 8080

RUN chmod 755 start.sh

CMD ["./start.sh", "logs"]
