# normal call
# docker build -f Dockerfile.py312.cuda --build-arg NVIDIA_DRIVER_PACKAGE= --build-arg NVIDIA_DRIVER_VERSION= --progress=plain -t bamborak_backend_cuda_minimal .

# rebuild from scratch
# <... same cmdline ...>  -t bamborak_backend_cuda_minimal . --no-cache

# ==============================
# Stage 1 – Builder
# ==============================
FROM ubuntu:noble AS bamborak_ubuntu_builder

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt/build

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-venv python3-pip \
    git pkgconf \
    libavformat-dev libavcodec-dev libavdevice-dev \
    libavutil-dev libavfilter-dev libswscale-dev libswresample-dev \
    ffmpeg \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# venv außerhalb vom App-Ordner (bessere Cachebarkeit)
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt /

RUN pip install -r /requirements_voice_changer.txt
RUN pip install Flask==3.1.2 flask-cors==6.0.1 beautifulsoup4 lxml

# ==============================
# Stage 2 – Runtime (minimal!)
# ==============================
FROM ubuntu:noble

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /usr/app/src

# try to force a fixed version
ARG NVIDIA_DRIVER_PACKAGE
ARG NVIDIA_DRIVER_VERSION

# nur Runtime-Libraries (KEINE dev!)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    libsndfile1 sox libsox-fmt-all \
    $NVIDIA_DRIVER_PACKAGE=$NVIDIA_DRIVER_VERSION \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# venv vom Builder übernehmen
COPY --from=bamborak_ubuntu_builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# App-Code zuletzt kopieren → C++ Rebuild nur bei Codeänderung
COPY . .

RUN mkdir -p logs temp tts_models voice_changer

EXPOSE 8080

RUN chmod 755 start.sh

CMD ["./start.sh", "logs"]
