number_words = {
    "hsb": {
        "0to9": {
            0: "nul",
            1: "jedyn",
            2: "dwaj",
            3: "tři",
            4: "štyri",
            5: "pjeć",
            6: "šěsć",
            7: "sydom",
            8: "wosom",
            9: "dźewjeć",
        },
        "10to19": {
            10: "dźesać",
            11: "jědnaće",
            12: "dwanaće",
            13: "třinaće",
            14: "štyrnaće",
            15: "pjatnaće",
            16: "šěsnaće",
            17: "sydomnaće",
            18: "wosomnaće",
            19: "dźewjatnaće",
        },
        "20to90": {
            2: "dwaceći",
            3: "třiceći",
            4: "štyrceći",
            5: "pjećdźesat",
            6: "šěsćdźesat",
            7: "sydomdźesat",
            8: "wosomdźesat",
            9: "dźewjećdźesat",
        },
        "100to900": {
            1: "sto",
            2: "dwěsćě",
            3: "třista",
            4: "štyrista",
            5: "pjećstow",
            6: "šěsćstow",
            7: "sydomstow",
            8: "wosomstow",
            9: "dźewjećstow",
        },
        "1000plus": {
            1e3: "tysac",
            1e6: "jedyn milion",  # milion maskulinum
            2e6: "dwaj milionaj",
            3e6: "tři miliony",
            4e6: "štyri miliony",
            5e6: "pjeć milionow",
            "6e6+": "milionow",
            1e9: "jedna miliarda",  # miliarda femininum
            2e9: "dwě miliardźe",
            3e9: "tři miliardy",
            4e9: "štyri miliardy",
            5e9: "pjeć miliardow",
            "6e9+": "miliardow",
            1e12: "jedyn bilion",  # bilion maskulinum
            2e12: "dwaj bilionaj",
            3e12: "tři biliony",
            4e12: "štyri biliony",
            5e12: "pjeć bilionow",
            "6e12+": "bilionow",
        }
    },
    "de": {
        "0to9": {
            0: "null",
            1: "eins",
            2: "zwei",
            3: "drei",
            4: "vier",
            5: "fünf",
            6: "sechs",
            7: "sieben",
            8: "acht",
            9: "neun",
        },
        "10to19": {
            10: "zehn",
            11: "elf",
            12: "zwölf",
            13: "dreizehn",
            14: "vierzehn",
            15: "fünfzehn",
            16: "sechzehn",
            17: "siebzehn",
            18: "achtzehn",
            19: "neunzehn",
        },
        "20to90": {
            2: "zwanzig",
            3: "dreißig",
            4: "vierzig",
            5: "fünfzig",
            6: "sechzig",
            7: "siebzig",
            8: "achtzig",
            9: "neunzig",
        },
        "100to900": {
            1: "einhundert",
            2: "zweihundert",
            3: "dreihundert",
            4: "vierhundert",
            5: "fünfhundert",
            6: "sechshundert",
            7: "siebenhundert",
            8: "achthundert",
            9: "neunhundert",
        },
        "1000plus": {
            1e3: "tausend",
            1e6: "eine Million",  # Million femininum
            2e6: "zwei Millionen",
            3e6: "drei Millionen",
            4e6: "vier Millionen",
            5e6: "fünf Millionen",
            "6e6+": "Millionen",
            1e9: "eine Milliarde",  # Milliarde femininum
            2e9: "zwei Milliarden",
            3e9: "drei Milliarden",
            4e9: "vier Milliarden",
            5e9: "fünf Milliarden",
            "6e9+": "Milliarden",
            1e12: "eine Billion",  # Billion femininum
            2e12: "zwei Billionen",
            3e12: "drei Billionen",
            4e12: "vier Billionen",
            5e12: "fünf Billionen",
            "6e12+": "Billionen",
        }
    }
}
